### ISSUE TITLE
Verification plan document?

### ISSUE THREAD

**Issue by Alex-Mann** [andres-mancera/ethernet_10ge_mac_SV_UVM_tb#1]
Where can I find the verification plan document?

**Comment by andres-mancera** [comment]
I did not realize that even though that document is mentioned in the README file, I did not actually push it GitHub.  I'm honestly not sure that it'll be useful though.  However, one of my other public repositories has a copy of the [Verification Plan document](https://github.com/andres-mancera/ethernet_10ge_mac_SV_tb/blob/master/doc/10GB_MAC_CORE_Verification_Plan.pdf).  Perhaps you want to take a look at that one?

**Comment by Alex-Mann** [comment]
This is great, thank you.

**Comment by andres-mancera** [comment]
👍
